name: CI

on:
    - pull_request

jobs:
    code-quality:
        name: Code quality checks
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Set up Python 3.8
              uses: actions/setup-python@v4
              with:
                  python-version: 3.8

            - uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dev dependencies
              run: |
                  python -m pip install -e .[dev]
              if: steps.cache.outputs.cache-hit != 'true'

            - name: Check formatting with black
              run: |
                  black --check .
            
            - name: Lint with flake8
              run: |
                  flake8 posthog --ignore E501

            - name: Check import order with isort
              run: |
                  isort --check-only .

    tests:
        name: Python tests
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install requirements.txt dependencies with pip
              run: |
                  python -m pip install -e .[test]

            - name: Run posthog tests
              run: |
                  python setup.py test
